version: "3"

services:

  # TerraMA2 Web Application
  webapp:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2-webapp:${TERRAMA2_TAG}"
    restart: "unless-stopped"
    ports:
      - "${TERRAMA2_WEBAPP_ADDRESS}:36000"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "terrama2_shared_vol:/shared-data"
      - "${TERRAMA2_CONFIG_DIR}/terrama2_webapp_db.json:/opt/terrama2/${TERRAMA2_TAG}/webapp/config/db.json"
      - "${TERRAMA2_CONFIG_DIR}/terrama2_webapp_settings.json:/opt/terrama2/${TERRAMA2_TAG}/webapp/config/settings.json"
    networks:
      - net

  # TerraMA2 Web Monitor
  webmonitor:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2-webmonitor:${TERRAMA2_TAG}"
    restart: "unless-stopped"
    ports:
      - "${TERRAMA2_WEBMONITOR_ADDRESS}:36001"
    depends_on:
      - webapp
    environment:
      - "NODE_TLS_REJECT_UNAUTHORIZED=0"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "terrama2_shared_vol:/shared-data"
      - "${TERRAMA2_CONFIG_DIR}/terrama2_webmonitor.json:/opt/terrama2/${TERRAMA2_TAG}/webmonitor/config/instances/default.json"
      - "${TERRAMA2_CONFIG_DIR}/terrama2_webmonitor_user_conf.json:/opt/terrama2/${TERRAMA2_TAG}/webmonitor/config/instances/user_conf.json"
      - "webmonitor_images:/opt/terrama2/${TERRAMA2_TAG}/webmonitor/public/images"
    networks:
      - net
    links:
      - webapp

networks:
  net:

volumes:
  data_vol:
  webmonitor_images:
  terrama2_shared_vol:
    external:
      name: terrama2_shared_vol
