version: "3"

services:
  
  # TerraMA2 Web Application
  webapp:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2-webapp:4.0.0-rc4"
    ports:
      - "${TERRAMA2_WEBAPP_ADDRESS}:36000"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "${TERRAMA2_CONFIG_DIR}/${TERRAMA2_PROJECT_NAME}_webapp.json:/opt/terrama2/4.0.0/webapp/config/instances/default.json"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa:/home/terrama2/.ssh/id_rsa"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa:/root/.ssh/id_rsa"
    networks:
      - net:

  # TerraMA2 Web Monitor
  webmonitor:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2-webmonitor:4.0.0-rc4"
    ports:
      - "${TERRAMA2_WEBMONITOR_ADDRESS}:36001"
    depends_on:
      - webapp
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "${TERRAMA2_CONFIG_DIR}/${TERRAMA2_PROJECT_NAME}_webmonitor.json:/opt/terrama2/4.0.0/webmonitor/config/instances/default.json"
    networks:
      - net
    links:
      - webapp

  # TerraMA2 Collector Service using TerraMA2 Base
  collector:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2:4.0.0-rc4"
    entrypoint: 
      - /usr/local/bin/start_terrama2_service.sh
      - COLLECTOR
      - "6543"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/home/terrama2/.ssh/authorized_keys"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/root/.ssh/authorized_keys"
    tty: true
    networks:
      - net

  # TerraMA2 Analysis Service using TerraMA2 Base
  analysis:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2:4.0.0-rc4"
    entrypoint: 
      - /usr/local/bin/start_terrama2_service.sh
      - ANALYSIS
      - "6544"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/home/terrama2/.ssh/authorized_keys"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/root/.ssh/authorized_keys"
    tty: true
    networks:
      - net

  # TerraMA2 View Service using TerraMA2 Base
  view:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2:4.0.0-rc4"
    entrypoint: 
      - /usr/local/bin/start_terrama2_service.sh
      - VIEW
      - "6545"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/home/terrama2/.ssh/authorized_keys"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/root/.ssh/authorized_keys"
    tty: true
    networks:
      - net

  # TerraMA2 Alert Service using TerraMA2 Base
  alert:
    image: "${TERRAMA2_DOCKER_REGISTRY}/terrama2:4.0.0-rc4"
    entrypoint: 
      - /usr/local/bin/start_terrama2_service.sh
      - ALERT
      - "6546"
    volumes:
      - "${TERRAMA2_DATA_DIR}:/data"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/home/terrama2/.ssh/authorized_keys"
      - "${TERRAMA2_CONFIG_DIR}/id_rsa.pub:/root/.ssh/authorized_keys"
    tty: true
    networks:
      - net

networks:

    net:
